# Generated by Django 5.2.4 on 2025-07-05 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('bank_id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_headquarter', models.TextField()),
                ('currency', models.CharField(max_length=10)),
                ('bank_country', models.CharField(max_length=10)),
                ('swift_code', models.CharField(max_length=11, unique=True)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('regulatory_authority', models.CharField(max_length=10)),
                ('bank_type', models.CharField(choices=[('COMMERCIAL', 'commercial'), ('CENTRAL', 'central'), ('INVESTMENT', 'investment'), ('OTHER', 'other')], max_length=16)),
                ('branch_ids', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=64, unique=True)),
                ('account_type', models.CharField(max_length=32)),
                ('currency', models.CharField(max_length=3)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('branch_id', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FROZEN', 'Frozen'), ('CLOSED', 'Closed')], max_length=16)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('watchlist_indicators', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='user_data.bankaccountuser')),
            ],
        ),
        migrations.CreateModel(
            name='CentralBank',
            fields=[
                ('banks_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='banks.banks')),
                ('monetary_policy_framework', models.TextField()),
                ('reserve_requirement_ratio', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            bases=('banks.banks',),
        ),
        migrations.CreateModel(
            name='CommercialBank',
            fields=[
                ('banks_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='banks.banks')),
                ('ifsc_code', models.CharField(max_length=11)),
                ('correspondent_swift_codes', models.JSONField(blank=True, default=list)),
            ],
            bases=('banks.banks',),
        ),
        migrations.CreateModel(
            name='CreditUnion',
            fields=[
                ('banks_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='banks.banks')),
                ('registration_number', models.CharField(max_length=64)),
                ('dividend_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            bases=('banks.banks',),
        ),
        migrations.CreateModel(
            name='InvestmentBank',
            fields=[
                ('banks_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='banks.banks')),
                ('underwriting_standards', models.TextField()),
                ('trading_desk_ids', models.JSONField(blank=True, default=list)),
                ('prime_brokerage_partners', models.JSONField(blank=True, default=list)),
            ],
            bases=('banks.banks',),
        ),
        migrations.CreateModel(
            name='RetailBank',
            fields=[
                ('banks_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='banks.banks')),
                ('branch_locations', models.JSONField(blank=True, default=list)),
                ('atm_network_id', models.CharField(max_length=64)),
                ('supported_card_networks', models.JSONField(blank=True, default=list)),
            ],
            bases=('banks.banks',),
        ),
        migrations.CreateModel(
            name='BankingProfessional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_id', models.CharField(max_length=64, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(choices=[('ANALYST', 'Analyst'), ('INVESTIGATOR', 'Investigator'), ('COMPLIANCE', 'Compliance Officer'), ('ADMIN', 'Admin'), ('AUDITOR', 'Auditor'), ('EXECUTIVE', 'Executive')], max_length=16)),
                ('employee_id', models.CharField(max_length=64)),
                ('permissions', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('DEACTIVATED', 'Deactivated')], default='ACTIVE', max_length=16)),
                ('auth_provider', models.CharField(default='Password', max_length=32)),
                ('preferred_language', models.CharField(default='en-US', max_length=10)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mfa_enabled', models.BooleanField(default=True)),
                ('security_clearance', models.CharField(default='Level1', max_length=16)),
                ('access_regions', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(limit_choices_to=models.Q(('banking_profile_isnull', True)), on_delete=django.db.models.deletion.CASCADE, related_name='banking_profile', to=settings.AUTH_USER_MODEL)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.banks')),
            ],
        ),
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stakeholder_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('stakeholder_type', models.CharField(choices=[('REGULATOR', 'Regulator'), ('AUDITOR', 'Auditor'), ('EXECUTIVE', 'Executive'), ('PARTNER_BANK', 'Partner Bank')], max_length=16)),
                ('organization', models.CharField(max_length=200)),
                ('contact_info', models.JSONField()),
                ('areas_of_interest', models.JSONField(blank=True, default=list)),
                ('regulated_banks', models.ManyToManyField(blank=True, related_name='regulators', to='banks.commercialbank')),
            ],
        ),
    ]
