# Generated by Django 5.2.3 on 2025-06-17 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankingprofessional',
            old_name='bank',
            new_name='bank_id',
        ),
    ]
