# Generated by Django 5.2.3 on 2025-06-17 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_rename_bank_bankingprofessional_bank_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankingprofessional',
            old_name='bank_id',
            new_name='bank',
        ),
    ]
