# Generated by Django 5.2.4 on 2025-07-05 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_alter_bankaccount_user'),
        ('user_data', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankAccountUser',
        ),
    ]
